version: '3.8'

services:
  app:
    build: 
      context: .
      args:
        - NODE_ENV=production
    ports:
      - "${PORT}:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/data/db.sqlite
    restart: unless-stopped

  dev:
    build:
      context: .
      args:
        - NODE_ENV=development
    ports:
      - "${PORT}:3000"
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    environment:
      - NODE_ENV=development
      - DB_PATH=/app/data/db.sqlite
    command: npm run dev 